### PR TITLE
fixed(general): provide nodejs and web versions as separate

### LINKED ISSUE #14: provide true nodejs based version
As for now, nodejs version does not work on backend

### PR DESCRIPTION
**Pull request by buchslava**
Closes #14

### CODE REVIEW

File: src/ws-reader-base.js [hunk 1]
```diff
@@ -16,171 +16,173 @@ const ERRORS = {
...
-      .catch(error => {
-        const options = {
-          query,
-          error,
-          ddfql,
-          endpoint: url,
-          homepoint
-        };
+    read(query, parsers = {}) {
+      const ddfql = isString(this._dataset)
```
Comment (korel-san) [inline src/ws-reader-base.js]: @buchslava query.dataset || this._dataset

File: src/ws-reader-base.js [hunk 2]
```diff
@@ -16,171 +16,173 @@ const ERRORS = {
...
+        ? Object.assign({}, query, { dataset: encodeURIComponent(this._dataset) })
```
Comment (korel-san) [inline src/ws-reader-base.js]: @buchslava query.dataset || this._dataset
